version: '3'
services:
  lb:
    image: traefik:v2.1
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  ui:
    build: ui
    labels:
      - "traefik.http.routers.ui.rule=PathPrefix(`/`)"
    environment:
      - "NODE_ENV=development"
    expose:
      - 5000
    volumes:
      - ./ui:/opt/node_app/app:delegated
      - ./ui/package.json:/opt/node_app/package.json
      - ./ui/package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules
    command: npm run dev
  api:
    build: api
    labels:
      - "traefik.http.routers.api.rule=PathPrefix(`/api/`)"
    environment:
      - "NODE_ENV=development"
    expose:
      - 3000
    volumes:
      - ./api:/opt/node_app/app:delegated
      - ./api/package.json:/opt/node_app/package.json
      - ./api/package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules
    command: npm start
volumes:
  notused: